package com.topshare.airshuttle.model.orderEvaluate;

/***
 * 订单流程表
 * @author root
 *
 */
public class TAirshuttleOrderEvaluate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_order_evaluate.id
     *
     * @mbggenerated Mon Jul 13 23:36:33 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_order_evaluate.parent_id
     *
     * @mbggenerated Mon Jul 13 23:36:33 CST 2015
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_order_evaluate.order_id
     *
     * @mbggenerated Mon Jul 13 23:36:33 CST 2015
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_order_evaluate.content
     *
     * @mbggenerated Mon Jul 13 23:36:33 CST 2015
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_order_evaluate.id
     *
     * @return the value of t_airshuttle_order_evaluate.id
     *
     * @mbggenerated Mon Jul 13 23:36:33 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_order_evaluate.id
     *
     * @param id the value for t_airshuttle_order_evaluate.id
     *
     * @mbggenerated Mon Jul 13 23:36:33 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_order_evaluate.parent_id
     *
     * @return the value of t_airshuttle_order_evaluate.parent_id
     *
     * @mbggenerated Mon Jul 13 23:36:33 CST 2015
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_order_evaluate.parent_id
     *
     * @param parentId the value for t_airshuttle_order_evaluate.parent_id
     *
     * @mbggenerated Mon Jul 13 23:36:33 CST 2015
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_order_evaluate.order_id
     *
     * @return the value of t_airshuttle_order_evaluate.order_id
     *
     * @mbggenerated Mon Jul 13 23:36:33 CST 2015
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_order_evaluate.order_id
     *
     * @param orderId the value for t_airshuttle_order_evaluate.order_id
     *
     * @mbggenerated Mon Jul 13 23:36:33 CST 2015
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_order_evaluate.content
     *
     * @return the value of t_airshuttle_order_evaluate.content
     *
     * @mbggenerated Mon Jul 13 23:36:33 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_order_evaluate.content
     *
     * @param content the value for t_airshuttle_order_evaluate.content
     *
     * @mbggenerated Mon Jul 13 23:36:33 CST 2015
     */
    public void setContent(String content) {
        this.content = content;
    }
}