package com.topshare.airshuttle.model.reviewProcess;

public class TAirshuttleReviewProcess {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_review_process.id
     *
     * @mbggenerated Mon Jul 13 21:23:33 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_review_process.module_desc
     *
     * @mbggenerated Mon Jul 13 21:23:33 CST 2015
     */
    private Integer moduleDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_review_process.module_id
     *
     * @mbggenerated Mon Jul 13 21:23:33 CST 2015
     */
    private Integer moduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_review_process.sort
     *
     * @mbggenerated Mon Jul 13 21:23:33 CST 2015
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_review_process.process_desc
     *
     * @mbggenerated Mon Jul 13 21:23:33 CST 2015
     */
    private String processDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_review_process.id
     *
     * @return the value of t_airshuttle_review_process.id
     *
     * @mbggenerated Mon Jul 13 21:23:33 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_review_process.id
     *
     * @param id the value for t_airshuttle_review_process.id
     *
     * @mbggenerated Mon Jul 13 21:23:33 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_review_process.module_desc
     *
     * @return the value of t_airshuttle_review_process.module_desc
     *
     * @mbggenerated Mon Jul 13 21:23:33 CST 2015
     */
    public Integer getModuleDesc() {
        return moduleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_review_process.module_desc
     *
     * @param moduleDesc the value for t_airshuttle_review_process.module_desc
     *
     * @mbggenerated Mon Jul 13 21:23:33 CST 2015
     */
    public void setModuleDesc(Integer moduleDesc) {
        this.moduleDesc = moduleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_review_process.module_id
     *
     * @return the value of t_airshuttle_review_process.module_id
     *
     * @mbggenerated Mon Jul 13 21:23:33 CST 2015
     */
    public Integer getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_review_process.module_id
     *
     * @param moduleId the value for t_airshuttle_review_process.module_id
     *
     * @mbggenerated Mon Jul 13 21:23:33 CST 2015
     */
    public void setModuleId(Integer moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_review_process.sort
     *
     * @return the value of t_airshuttle_review_process.sort
     *
     * @mbggenerated Mon Jul 13 21:23:33 CST 2015
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_review_process.sort
     *
     * @param sort the value for t_airshuttle_review_process.sort
     *
     * @mbggenerated Mon Jul 13 21:23:33 CST 2015
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_review_process.process_desc
     *
     * @return the value of t_airshuttle_review_process.process_desc
     *
     * @mbggenerated Mon Jul 13 21:23:33 CST 2015
     */
    public String getProcessDesc() {
        return processDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_review_process.process_desc
     *
     * @param processDesc the value for t_airshuttle_review_process.process_desc
     *
     * @mbggenerated Mon Jul 13 21:23:33 CST 2015
     */
    public void setProcessDesc(String processDesc) {
        this.processDesc = processDesc;
    }
}