package com.topshare.airshuttle.model.flyGroup;

import java.util.Date;

public class TAirshuttleFlyGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_fly_group.id
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_fly_group.Designation_number
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    private String designationNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_fly_group.CREATE_PERSON
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    private Integer createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_fly_group.CREATE_TIME
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_fly_group.MODIFY_PERSON
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    private Integer modifyPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_fly_group.MODIFY_TIME
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_fly_group.Admission_school
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    private String admissionSchool;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_fly_group.group_type
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    private Integer groupType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_fly_group.origin
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    private String origin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_fly_group.destination
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    private String destination;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_fly_group.group_name
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_fly_group.max_member
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    private Integer maxMember;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_fly_group.expiration_date
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    private Date expirationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_fly_group.contact_information
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    private String contactInformation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_fly_group.memo
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_fly_group.is_Book_flights
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    private Integer isBookFlights;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_fly_group.book_flights_id
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    private Integer bookFlightsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_fly_group.depart_time
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    private Date departTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_fly_group.arrive_time
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    private Date arriveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_fly_group.airlines
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    private String airlines;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_fly_group.flight
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    private String flight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_fly_group.depart_airport
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    private String departAirport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_fly_group.arrive_airport
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    private String arriveAirport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_fly_group.is_book_pick_up_airport
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    private Integer isBookPickUpAirport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_fly_group.book_car_number
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    private Integer bookCarNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_fly_group.carry_number_person
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    private Integer carryNumberPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_fly_group.driver_list
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    private String driverList;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_fly_group.id
     *
     * @return the value of t_airshuttle_fly_group.id
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_fly_group.id
     *
     * @param id the value for t_airshuttle_fly_group.id
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_fly_group.Designation_number
     *
     * @return the value of t_airshuttle_fly_group.Designation_number
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public String getDesignationNumber() {
        return designationNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_fly_group.Designation_number
     *
     * @param designationNumber the value for t_airshuttle_fly_group.Designation_number
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public void setDesignationNumber(String designationNumber) {
        this.designationNumber = designationNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_fly_group.CREATE_PERSON
     *
     * @return the value of t_airshuttle_fly_group.CREATE_PERSON
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public Integer getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_fly_group.CREATE_PERSON
     *
     * @param createPerson the value for t_airshuttle_fly_group.CREATE_PERSON
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public void setCreatePerson(Integer createPerson) {
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_fly_group.CREATE_TIME
     *
     * @return the value of t_airshuttle_fly_group.CREATE_TIME
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_fly_group.CREATE_TIME
     *
     * @param createTime the value for t_airshuttle_fly_group.CREATE_TIME
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_fly_group.MODIFY_PERSON
     *
     * @return the value of t_airshuttle_fly_group.MODIFY_PERSON
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public Integer getModifyPerson() {
        return modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_fly_group.MODIFY_PERSON
     *
     * @param modifyPerson the value for t_airshuttle_fly_group.MODIFY_PERSON
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public void setModifyPerson(Integer modifyPerson) {
        this.modifyPerson = modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_fly_group.MODIFY_TIME
     *
     * @return the value of t_airshuttle_fly_group.MODIFY_TIME
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_fly_group.MODIFY_TIME
     *
     * @param modifyTime the value for t_airshuttle_fly_group.MODIFY_TIME
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_fly_group.Admission_school
     *
     * @return the value of t_airshuttle_fly_group.Admission_school
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public String getAdmissionSchool() {
        return admissionSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_fly_group.Admission_school
     *
     * @param admissionSchool the value for t_airshuttle_fly_group.Admission_school
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public void setAdmissionSchool(String admissionSchool) {
        this.admissionSchool = admissionSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_fly_group.group_type
     *
     * @return the value of t_airshuttle_fly_group.group_type
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public Integer getGroupType() {
        return groupType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_fly_group.group_type
     *
     * @param groupType the value for t_airshuttle_fly_group.group_type
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public void setGroupType(Integer groupType) {
        this.groupType = groupType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_fly_group.origin
     *
     * @return the value of t_airshuttle_fly_group.origin
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_fly_group.origin
     *
     * @param origin the value for t_airshuttle_fly_group.origin
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public void setOrigin(String origin) {
        this.origin = origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_fly_group.destination
     *
     * @return the value of t_airshuttle_fly_group.destination
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public String getDestination() {
        return destination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_fly_group.destination
     *
     * @param destination the value for t_airshuttle_fly_group.destination
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public void setDestination(String destination) {
        this.destination = destination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_fly_group.group_name
     *
     * @return the value of t_airshuttle_fly_group.group_name
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_fly_group.group_name
     *
     * @param groupName the value for t_airshuttle_fly_group.group_name
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_fly_group.max_member
     *
     * @return the value of t_airshuttle_fly_group.max_member
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public Integer getMaxMember() {
        return maxMember;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_fly_group.max_member
     *
     * @param maxMember the value for t_airshuttle_fly_group.max_member
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public void setMaxMember(Integer maxMember) {
        this.maxMember = maxMember;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_fly_group.expiration_date
     *
     * @return the value of t_airshuttle_fly_group.expiration_date
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public Date getExpirationDate() {
        return expirationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_fly_group.expiration_date
     *
     * @param expirationDate the value for t_airshuttle_fly_group.expiration_date
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public void setExpirationDate(Date expirationDate) {
        this.expirationDate = expirationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_fly_group.contact_information
     *
     * @return the value of t_airshuttle_fly_group.contact_information
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public String getContactInformation() {
        return contactInformation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_fly_group.contact_information
     *
     * @param contactInformation the value for t_airshuttle_fly_group.contact_information
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public void setContactInformation(String contactInformation) {
        this.contactInformation = contactInformation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_fly_group.memo
     *
     * @return the value of t_airshuttle_fly_group.memo
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_fly_group.memo
     *
     * @param memo the value for t_airshuttle_fly_group.memo
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_fly_group.is_Book_flights
     *
     * @return the value of t_airshuttle_fly_group.is_Book_flights
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public Integer getIsBookFlights() {
        return isBookFlights;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_fly_group.is_Book_flights
     *
     * @param isBookFlights the value for t_airshuttle_fly_group.is_Book_flights
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public void setIsBookFlights(Integer isBookFlights) {
        this.isBookFlights = isBookFlights;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_fly_group.book_flights_id
     *
     * @return the value of t_airshuttle_fly_group.book_flights_id
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public Integer getBookFlightsId() {
        return bookFlightsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_fly_group.book_flights_id
     *
     * @param bookFlightsId the value for t_airshuttle_fly_group.book_flights_id
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public void setBookFlightsId(Integer bookFlightsId) {
        this.bookFlightsId = bookFlightsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_fly_group.depart_time
     *
     * @return the value of t_airshuttle_fly_group.depart_time
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public Date getDepartTime() {
        return departTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_fly_group.depart_time
     *
     * @param departTime the value for t_airshuttle_fly_group.depart_time
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public void setDepartTime(Date departTime) {
        this.departTime = departTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_fly_group.arrive_time
     *
     * @return the value of t_airshuttle_fly_group.arrive_time
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public Date getArriveTime() {
        return arriveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_fly_group.arrive_time
     *
     * @param arriveTime the value for t_airshuttle_fly_group.arrive_time
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public void setArriveTime(Date arriveTime) {
        this.arriveTime = arriveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_fly_group.airlines
     *
     * @return the value of t_airshuttle_fly_group.airlines
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public String getAirlines() {
        return airlines;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_fly_group.airlines
     *
     * @param airlines the value for t_airshuttle_fly_group.airlines
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public void setAirlines(String airlines) {
        this.airlines = airlines;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_fly_group.flight
     *
     * @return the value of t_airshuttle_fly_group.flight
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public String getFlight() {
        return flight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_fly_group.flight
     *
     * @param flight the value for t_airshuttle_fly_group.flight
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public void setFlight(String flight) {
        this.flight = flight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_fly_group.depart_airport
     *
     * @return the value of t_airshuttle_fly_group.depart_airport
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public String getDepartAirport() {
        return departAirport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_fly_group.depart_airport
     *
     * @param departAirport the value for t_airshuttle_fly_group.depart_airport
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public void setDepartAirport(String departAirport) {
        this.departAirport = departAirport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_fly_group.arrive_airport
     *
     * @return the value of t_airshuttle_fly_group.arrive_airport
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public String getArriveAirport() {
        return arriveAirport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_fly_group.arrive_airport
     *
     * @param arriveAirport the value for t_airshuttle_fly_group.arrive_airport
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public void setArriveAirport(String arriveAirport) {
        this.arriveAirport = arriveAirport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_fly_group.is_book_pick_up_airport
     *
     * @return the value of t_airshuttle_fly_group.is_book_pick_up_airport
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public Integer getIsBookPickUpAirport() {
        return isBookPickUpAirport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_fly_group.is_book_pick_up_airport
     *
     * @param isBookPickUpAirport the value for t_airshuttle_fly_group.is_book_pick_up_airport
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public void setIsBookPickUpAirport(Integer isBookPickUpAirport) {
        this.isBookPickUpAirport = isBookPickUpAirport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_fly_group.book_car_number
     *
     * @return the value of t_airshuttle_fly_group.book_car_number
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public Integer getBookCarNumber() {
        return bookCarNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_fly_group.book_car_number
     *
     * @param bookCarNumber the value for t_airshuttle_fly_group.book_car_number
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public void setBookCarNumber(Integer bookCarNumber) {
        this.bookCarNumber = bookCarNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_fly_group.carry_number_person
     *
     * @return the value of t_airshuttle_fly_group.carry_number_person
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public Integer getCarryNumberPerson() {
        return carryNumberPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_fly_group.carry_number_person
     *
     * @param carryNumberPerson the value for t_airshuttle_fly_group.carry_number_person
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public void setCarryNumberPerson(Integer carryNumberPerson) {
        this.carryNumberPerson = carryNumberPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_fly_group.driver_list
     *
     * @return the value of t_airshuttle_fly_group.driver_list
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public String getDriverList() {
        return driverList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_fly_group.driver_list
     *
     * @param driverList the value for t_airshuttle_fly_group.driver_list
     *
     * @mbggenerated Tue Jul 21 11:08:44 CST 2015
     */
    public void setDriverList(String driverList) {
        this.driverList = driverList;
    }
   public String toString(){
	return "groupName:"+groupName;
    	
    }
}