package com.topshare.airshuttle.model.myCollection;

import java.util.Date;

public class TAirshuttleMyCollection {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_my_collection.id
     *
     * @mbggenerated Mon Jul 13 15:42:14 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_my_collection.ref_id
     *
     * @mbggenerated Mon Jul 13 15:42:14 CST 2015
     */
    private Integer refId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_my_collection.type
     *
     * @mbggenerated Mon Jul 13 15:42:14 CST 2015
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_my_collection.user_id
     *
     * @mbggenerated Mon Jul 13 15:42:14 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_my_collection.CREATE_TIME
     *
     * @mbggenerated Mon Jul 13 15:42:14 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_my_collection.MODIFY_TIME
     *
     * @mbggenerated Mon Jul 13 15:42:14 CST 2015
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_my_collection.id
     *
     * @return the value of t_airshuttle_my_collection.id
     *
     * @mbggenerated Mon Jul 13 15:42:14 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_my_collection.id
     *
     * @param id the value for t_airshuttle_my_collection.id
     *
     * @mbggenerated Mon Jul 13 15:42:14 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_my_collection.ref_id
     *
     * @return the value of t_airshuttle_my_collection.ref_id
     *
     * @mbggenerated Mon Jul 13 15:42:14 CST 2015
     */
    public Integer getRefId() {
        return refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_my_collection.ref_id
     *
     * @param refId the value for t_airshuttle_my_collection.ref_id
     *
     * @mbggenerated Mon Jul 13 15:42:14 CST 2015
     */
    public void setRefId(Integer refId) {
        this.refId = refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_my_collection.type
     *
     * @return the value of t_airshuttle_my_collection.type
     *
     * @mbggenerated Mon Jul 13 15:42:14 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_my_collection.type
     *
     * @param type the value for t_airshuttle_my_collection.type
     *
     * @mbggenerated Mon Jul 13 15:42:14 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_my_collection.user_id
     *
     * @return the value of t_airshuttle_my_collection.user_id
     *
     * @mbggenerated Mon Jul 13 15:42:14 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_my_collection.user_id
     *
     * @param userId the value for t_airshuttle_my_collection.user_id
     *
     * @mbggenerated Mon Jul 13 15:42:14 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_my_collection.CREATE_TIME
     *
     * @return the value of t_airshuttle_my_collection.CREATE_TIME
     *
     * @mbggenerated Mon Jul 13 15:42:14 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_my_collection.CREATE_TIME
     *
     * @param createTime the value for t_airshuttle_my_collection.CREATE_TIME
     *
     * @mbggenerated Mon Jul 13 15:42:14 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_my_collection.MODIFY_TIME
     *
     * @return the value of t_airshuttle_my_collection.MODIFY_TIME
     *
     * @mbggenerated Mon Jul 13 15:42:14 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_my_collection.MODIFY_TIME
     *
     * @param modifyTime the value for t_airshuttle_my_collection.MODIFY_TIME
     *
     * @mbggenerated Mon Jul 13 15:42:14 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}