package com.topshare.airshuttle.model.bookGroup;

import java.util.Date;

/***
 * 用户报名飞友团，室友团
 * @author root
 *
 */
public class TAirshuttleUserBookGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_user_book_group.id
     *
     * @mbggenerated Mon Jul 13 16:20:06 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_user_book_group.book_time
     *
     * @mbggenerated Mon Jul 13 16:20:06 CST 2015
     */
    private Date bookTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_user_book_group.MODIFY_TIME
     *
     * @mbggenerated Mon Jul 13 16:20:06 CST 2015
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_user_book_group.type
     *
     * @mbggenerated Mon Jul 13 16:20:06 CST 2015
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_user_book_group.user_id
     *
     * @mbggenerated Mon Jul 13 16:20:06 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_user_book_group.ref_id
     *
     * @mbggenerated Mon Jul 13 16:20:06 CST 2015
     */
    private Integer refId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_user_book_group.status
     *
     * @mbggenerated Mon Jul 13 16:20:06 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_user_book_group.status_msg
     *
     * @mbggenerated Mon Jul 13 16:20:06 CST 2015
     */
    private String statusMsg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_user_book_group.id
     *
     * @return the value of t_airshuttle_user_book_group.id
     *
     * @mbggenerated Mon Jul 13 16:20:06 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_user_book_group.id
     *
     * @param id the value for t_airshuttle_user_book_group.id
     *
     * @mbggenerated Mon Jul 13 16:20:06 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_user_book_group.book_time
     *
     * @return the value of t_airshuttle_user_book_group.book_time
     *
     * @mbggenerated Mon Jul 13 16:20:06 CST 2015
     */
    public Date getBookTime() {
        return bookTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_user_book_group.book_time
     *
     * @param bookTime the value for t_airshuttle_user_book_group.book_time
     *
     * @mbggenerated Mon Jul 13 16:20:06 CST 2015
     */
    public void setBookTime(Date bookTime) {
        this.bookTime = bookTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_user_book_group.MODIFY_TIME
     *
     * @return the value of t_airshuttle_user_book_group.MODIFY_TIME
     *
     * @mbggenerated Mon Jul 13 16:20:06 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_user_book_group.MODIFY_TIME
     *
     * @param modifyTime the value for t_airshuttle_user_book_group.MODIFY_TIME
     *
     * @mbggenerated Mon Jul 13 16:20:06 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_user_book_group.type
     *
     * @return the value of t_airshuttle_user_book_group.type
     *
     * @mbggenerated Mon Jul 13 16:20:06 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_user_book_group.type
     *
     * @param type the value for t_airshuttle_user_book_group.type
     *
     * @mbggenerated Mon Jul 13 16:20:06 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_user_book_group.user_id
     *
     * @return the value of t_airshuttle_user_book_group.user_id
     *
     * @mbggenerated Mon Jul 13 16:20:06 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_user_book_group.user_id
     *
     * @param userId the value for t_airshuttle_user_book_group.user_id
     *
     * @mbggenerated Mon Jul 13 16:20:06 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_user_book_group.ref_id
     *
     * @return the value of t_airshuttle_user_book_group.ref_id
     *
     * @mbggenerated Mon Jul 13 16:20:06 CST 2015
     */
    public Integer getRefId() {
        return refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_user_book_group.ref_id
     *
     * @param refId the value for t_airshuttle_user_book_group.ref_id
     *
     * @mbggenerated Mon Jul 13 16:20:06 CST 2015
     */
    public void setRefId(Integer refId) {
        this.refId = refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_user_book_group.status
     *
     * @return the value of t_airshuttle_user_book_group.status
     *
     * @mbggenerated Mon Jul 13 16:20:06 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_user_book_group.status
     *
     * @param status the value for t_airshuttle_user_book_group.status
     *
     * @mbggenerated Mon Jul 13 16:20:06 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_user_book_group.status_msg
     *
     * @return the value of t_airshuttle_user_book_group.status_msg
     *
     * @mbggenerated Mon Jul 13 16:20:06 CST 2015
     */
    public String getStatusMsg() {
        return statusMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_user_book_group.status_msg
     *
     * @param statusMsg the value for t_airshuttle_user_book_group.status_msg
     *
     * @mbggenerated Mon Jul 13 16:20:06 CST 2015
     */
    public void setStatusMsg(String statusMsg) {
        this.statusMsg = statusMsg;
    }
}