package com.topshare.airshuttle.model.driver;

import java.util.Date;

/***
 * 司机和车辆关联表
 * @author root
 *
 */
public class TAirshuttleDriverCar {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_driver_car.driver_id
     *
     * @mbggenerated Wed Jul 08 10:34:35 CST 2015
     */
    private Integer driverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_driver_car.car_id
     *
     * @mbggenerated Wed Jul 08 10:34:35 CST 2015
     */
    private Integer carId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_driver_car.MODIFY_TIME
     *
     * @mbggenerated Wed Jul 08 10:34:35 CST 2015
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_driver_car.driver_id
     *
     * @return the value of t_airshuttle_driver_car.driver_id
     *
     * @mbggenerated Wed Jul 08 10:34:35 CST 2015
     */
    public Integer getDriverId() {
        return driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_driver_car.driver_id
     *
     * @param driverId the value for t_airshuttle_driver_car.driver_id
     *
     * @mbggenerated Wed Jul 08 10:34:35 CST 2015
     */
    public void setDriverId(Integer driverId) {
        this.driverId = driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_driver_car.car_id
     *
     * @return the value of t_airshuttle_driver_car.car_id
     *
     * @mbggenerated Wed Jul 08 10:34:35 CST 2015
     */
    public Integer getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_driver_car.car_id
     *
     * @param carId the value for t_airshuttle_driver_car.car_id
     *
     * @mbggenerated Wed Jul 08 10:34:35 CST 2015
     */
    public void setCarId(Integer carId) {
        this.carId = carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_driver_car.MODIFY_TIME
     *
     * @return the value of t_airshuttle_driver_car.MODIFY_TIME
     *
     * @mbggenerated Wed Jul 08 10:34:35 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_driver_car.MODIFY_TIME
     *
     * @param modifyTime the value for t_airshuttle_driver_car.MODIFY_TIME
     *
     * @mbggenerated Wed Jul 08 10:34:35 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}