package com.topshare.airshuttle.model.driver;

import java.util.Date;

public class TAirshuttleDriver {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_airshuttle_driver.id
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_airshuttle_driver.CREATE_PERSON
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	private Integer createPerson;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_airshuttle_driver.CREATE_TIME
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_airshuttle_driver.MODIFY_PERSON
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	private Integer modifyPerson;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_airshuttle_driver.MODIFY_TIME
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	private Date modifyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_airshuttle_driver.DESCRIPTION
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_airshuttle_driver.realName
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	private String realname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_airshuttle_driver.idCard
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	private String idcard;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_airshuttle_driver.telephone
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	private String telephone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_airshuttle_driver.driving_license_url
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	private String drivingLicenseUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_airshuttle_driver.Drivers_license_url
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	private String driversLicenseUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_airshuttle_driver.security_money
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	private String securityMoney;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_airshuttle_driver.official_photot_url
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	private String officialPhototUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_airshuttle_driver.status
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_airshuttle_driver.status_msg
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	private String statusMsg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_airshuttle_driver.city
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	private String city;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_airshuttle_driver.id
	 * @return  the value of t_airshuttle_driver.id
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_airshuttle_driver.id
	 * @param id  the value for t_airshuttle_driver.id
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_airshuttle_driver.CREATE_PERSON
	 * @return  the value of t_airshuttle_driver.CREATE_PERSON
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	public Integer getCreatePerson() {
		return createPerson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_airshuttle_driver.CREATE_PERSON
	 * @param createPerson  the value for t_airshuttle_driver.CREATE_PERSON
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	public void setCreatePerson(Integer createPerson) {
		this.createPerson = createPerson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_airshuttle_driver.CREATE_TIME
	 * @return  the value of t_airshuttle_driver.CREATE_TIME
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_airshuttle_driver.CREATE_TIME
	 * @param createTime  the value for t_airshuttle_driver.CREATE_TIME
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_airshuttle_driver.MODIFY_PERSON
	 * @return  the value of t_airshuttle_driver.MODIFY_PERSON
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	public Integer getModifyPerson() {
		return modifyPerson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_airshuttle_driver.MODIFY_PERSON
	 * @param modifyPerson  the value for t_airshuttle_driver.MODIFY_PERSON
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	public void setModifyPerson(Integer modifyPerson) {
		this.modifyPerson = modifyPerson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_airshuttle_driver.MODIFY_TIME
	 * @return  the value of t_airshuttle_driver.MODIFY_TIME
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_airshuttle_driver.MODIFY_TIME
	 * @param modifyTime  the value for t_airshuttle_driver.MODIFY_TIME
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_airshuttle_driver.DESCRIPTION
	 * @return  the value of t_airshuttle_driver.DESCRIPTION
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_airshuttle_driver.DESCRIPTION
	 * @param description  the value for t_airshuttle_driver.DESCRIPTION
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_airshuttle_driver.realName
	 * @return  the value of t_airshuttle_driver.realName
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	public String getRealname() {
		return realname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_airshuttle_driver.realName
	 * @param realname  the value for t_airshuttle_driver.realName
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	public void setRealname(String realname) {
		this.realname = realname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_airshuttle_driver.idCard
	 * @return  the value of t_airshuttle_driver.idCard
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	public String getIdcard() {
		return idcard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_airshuttle_driver.idCard
	 * @param idcard  the value for t_airshuttle_driver.idCard
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	public void setIdcard(String idcard) {
		this.idcard = idcard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_airshuttle_driver.telephone
	 * @return  the value of t_airshuttle_driver.telephone
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	public String getTelephone() {
		return telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_airshuttle_driver.telephone
	 * @param telephone  the value for t_airshuttle_driver.telephone
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_airshuttle_driver.driving_license_url
	 * @return  the value of t_airshuttle_driver.driving_license_url
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	public String getDrivingLicenseUrl() {
		return drivingLicenseUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_airshuttle_driver.driving_license_url
	 * @param drivingLicenseUrl  the value for t_airshuttle_driver.driving_license_url
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	public void setDrivingLicenseUrl(String drivingLicenseUrl) {
		this.drivingLicenseUrl = drivingLicenseUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_airshuttle_driver.Drivers_license_url
	 * @return  the value of t_airshuttle_driver.Drivers_license_url
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	public String getDriversLicenseUrl() {
		return driversLicenseUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_airshuttle_driver.Drivers_license_url
	 * @param driversLicenseUrl  the value for t_airshuttle_driver.Drivers_license_url
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	public void setDriversLicenseUrl(String driversLicenseUrl) {
		this.driversLicenseUrl = driversLicenseUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_airshuttle_driver.security_money
	 * @return  the value of t_airshuttle_driver.security_money
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	public String getSecurityMoney() {
		return securityMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_airshuttle_driver.security_money
	 * @param securityMoney  the value for t_airshuttle_driver.security_money
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	public void setSecurityMoney(String securityMoney) {
		this.securityMoney = securityMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_airshuttle_driver.official_photot_url
	 * @return  the value of t_airshuttle_driver.official_photot_url
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	public String getOfficialPhototUrl() {
		return officialPhototUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_airshuttle_driver.official_photot_url
	 * @param officialPhototUrl  the value for t_airshuttle_driver.official_photot_url
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	public void setOfficialPhototUrl(String officialPhototUrl) {
		this.officialPhototUrl = officialPhototUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_airshuttle_driver.status
	 * @return  the value of t_airshuttle_driver.status
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_airshuttle_driver.status
	 * @param status  the value for t_airshuttle_driver.status
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_airshuttle_driver.status_msg
	 * @return  the value of t_airshuttle_driver.status_msg
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	public String getStatusMsg() {
		return statusMsg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_airshuttle_driver.status_msg
	 * @param statusMsg  the value for t_airshuttle_driver.status_msg
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	public void setStatusMsg(String statusMsg) {
		this.statusMsg = statusMsg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_airshuttle_driver.city
	 * @return  the value of t_airshuttle_driver.city
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_airshuttle_driver.city
	 * @param city  the value for t_airshuttle_driver.city
	 * @mbggenerated  Tue Jul 21 15:13:18 CST 2015
	 */
	public void setCity(String city) {
		this.city = city;
	}
}