package com.topshare.airshuttle.model.order;

import java.util.Date;

public class TAirshuttleOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_order.id
     *
     * @mbggenerated Thu Jul 23 15:24:50 CST 2015
     */
    private Integer id;
    private Integer bookId;

    public Integer getBookId() {
		return bookId;
	}

	public void setBookId(Integer bookId) {
		this.bookId = bookId;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_order.Designation_number
     *
     * @mbggenerated Thu Jul 23 15:24:50 CST 2015
     */
    private String designationNumber;
    private Integer reviewProcessId;   //belong to orderprocess
 
    public Integer getReviewProcessId() {
		return reviewProcessId;
	}

	public void setReviewProcessId(Integer reviewProcessId) {
		this.reviewProcessId = reviewProcessId;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_order.create_time
     *
     * @mbggenerated Thu Jul 23 15:24:50 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_order.MODIFY_TIME
     *
     * @mbggenerated Thu Jul 23 15:24:50 CST 2015
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_order.user_id
     *
     * @mbggenerated Thu Jul 23 15:24:50 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_order.driver_id
     *
     * @mbggenerated Thu Jul 23 15:24:50 CST 2015
     */
    private Integer driverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_order.reception_air_id
     *
     * @mbggenerated Thu Jul 23 15:24:50 CST 2015
     */
    private Integer receptionAirId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_order.book_number_person
     *
     * @mbggenerated Thu Jul 23 15:24:50 CST 2015
     */
    private Integer bookNumberPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_order.pick_up_time
     *
     * @mbggenerated Thu Jul 23 15:24:50 CST 2015
     */
    private Date pickUpTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_order.book_price
     *
     * @mbggenerated Thu Jul 23 15:24:50 CST 2015
     */
    private String bookPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_order.id
     *
     * @return the value of t_airshuttle_order.id
     *
     * @mbggenerated Thu Jul 23 15:24:50 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_order.id
     *
     * @param id the value for t_airshuttle_order.id
     *
     * @mbggenerated Thu Jul 23 15:24:50 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_order.Designation_number
     *
     * @return the value of t_airshuttle_order.Designation_number
     *
     * @mbggenerated Thu Jul 23 15:24:50 CST 2015
     */
    public String getDesignationNumber() {
        return designationNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_order.Designation_number
     *
     * @param designationNumber the value for t_airshuttle_order.Designation_number
     *
     * @mbggenerated Thu Jul 23 15:24:50 CST 2015
     */
    public void setDesignationNumber(String designationNumber) {
        this.designationNumber = designationNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_order.create_time
     *
     * @return the value of t_airshuttle_order.create_time
     *
     * @mbggenerated Thu Jul 23 15:24:50 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_order.create_time
     *
     * @param createTime the value for t_airshuttle_order.create_time
     *
     * @mbggenerated Thu Jul 23 15:24:50 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_order.MODIFY_TIME
     *
     * @return the value of t_airshuttle_order.MODIFY_TIME
     *
     * @mbggenerated Thu Jul 23 15:24:50 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_order.MODIFY_TIME
     *
     * @param modifyTime the value for t_airshuttle_order.MODIFY_TIME
     *
     * @mbggenerated Thu Jul 23 15:24:50 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_order.user_id
     *
     * @return the value of t_airshuttle_order.user_id
     *
     * @mbggenerated Thu Jul 23 15:24:50 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_order.user_id
     *
     * @param userId the value for t_airshuttle_order.user_id
     *
     * @mbggenerated Thu Jul 23 15:24:50 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_order.driver_id
     *
     * @return the value of t_airshuttle_order.driver_id
     *
     * @mbggenerated Thu Jul 23 15:24:50 CST 2015
     */
    public Integer getDriverId() {
        return driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_order.driver_id
     *
     * @param driverId the value for t_airshuttle_order.driver_id
     *
     * @mbggenerated Thu Jul 23 15:24:50 CST 2015
     */
    public void setDriverId(Integer driverId) {
        this.driverId = driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_order.reception_air_id
     *
     * @return the value of t_airshuttle_order.reception_air_id
     *
     * @mbggenerated Thu Jul 23 15:24:50 CST 2015
     */
    public Integer getReceptionAirId() {
        return receptionAirId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_order.reception_air_id
     *
     * @param receptionAirId the value for t_airshuttle_order.reception_air_id
     *
     * @mbggenerated Thu Jul 23 15:24:50 CST 2015
     */
    public void setReceptionAirId(Integer receptionAirId) {
        this.receptionAirId = receptionAirId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_order.book_number_person
     *
     * @return the value of t_airshuttle_order.book_number_person
     *
     * @mbggenerated Thu Jul 23 15:24:50 CST 2015
     */
    public Integer getBookNumberPerson() {
        return bookNumberPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_order.book_number_person
     *
     * @param bookNumberPerson the value for t_airshuttle_order.book_number_person
     *
     * @mbggenerated Thu Jul 23 15:24:50 CST 2015
     */
    public void setBookNumberPerson(Integer bookNumberPerson) {
        this.bookNumberPerson = bookNumberPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_order.pick_up_time
     *
     * @return the value of t_airshuttle_order.pick_up_time
     *
     * @mbggenerated Thu Jul 23 15:24:50 CST 2015
     */
    public Date getPickUpTime() {
        return pickUpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_order.pick_up_time
     *
     * @param pickUpTime the value for t_airshuttle_order.pick_up_time
     *
     * @mbggenerated Thu Jul 23 15:24:50 CST 2015
     */
    public void setPickUpTime(Date pickUpTime) {
        this.pickUpTime = pickUpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_order.book_price
     *
     * @return the value of t_airshuttle_order.book_price
     *
     * @mbggenerated Thu Jul 23 15:24:50 CST 2015
     */
    public String getBookPrice() {
        return bookPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_order.book_price
     *
     * @param bookPrice the value for t_airshuttle_order.book_price
     *
     * @mbggenerated Thu Jul 23 15:24:50 CST 2015
     */
    public void setBookPrice(String bookPrice) {
        this.bookPrice = bookPrice;
    }
}