package com.topshare.airshuttle.model.receptionAir;

import java.util.Date;

public class TAirshuttleReceptionAir {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_reception_air.id
     *
     * @mbggenerated Wed Jul 22 14:46:31 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_reception_air.CREATE_PERSON
     *
     * @mbggenerated Wed Jul 22 14:46:31 CST 2015
     */
    private Integer createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_reception_air.CREATE_TIME
     *
     * @mbggenerated Wed Jul 22 14:46:31 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_reception_air.MODIFY_PERSON
     *
     * @mbggenerated Wed Jul 22 14:46:31 CST 2015
     */
    private Integer modifyPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_reception_air.MODIFY_TIME
     *
     * @mbggenerated Wed Jul 22 14:46:31 CST 2015
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_reception_air.reception_city
     *
     * @mbggenerated Wed Jul 22 14:46:31 CST 2015
     */
    private String drivingLicenseUrl;
    public String getDrivingLicenseUrl() {
		return drivingLicenseUrl;
	}

	public void setDrivingLicenseUrl(String drivingLicenseUrl) {
		this.drivingLicenseUrl = drivingLicenseUrl;
	}

	private String receptionCity;
public String getRealname() {
		return realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

private String realname;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_reception_air.reception_school
     *
     * @mbggenerated Wed Jul 22 14:46:31 CST 2015
     */
    private String receptionSchool;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_reception_air.reception_airport
     *
     * @mbggenerated Wed Jul 22 14:46:31 CST 2015
     */
    private String receptionAirport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_reception_air.driver_id
     *
     * @mbggenerated Wed Jul 22 14:46:31 CST 2015
     */
    private Integer driverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_reception_air.car_id
     *
     * @mbggenerated Wed Jul 22 14:46:31 CST 2015
     */
    private Integer carId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_reception_air.open_time
     *
     * @mbggenerated Wed Jul 22 14:46:31 CST 2015
     */
    private String openTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_reception_air.price
     *
     * @mbggenerated Wed Jul 22 14:46:31 CST 2015
     */
    private String price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_reception_air.load_seatNum
     *
     * @mbggenerated Wed Jul 22 14:46:31 CST 2015
     */
    private Integer loadSeatnum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_reception_air.id
     *
     * @return the value of t_airshuttle_reception_air.id
     *
     * @mbggenerated Wed Jul 22 14:46:31 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_reception_air.id
     *
     * @param id the value for t_airshuttle_reception_air.id
     *
     * @mbggenerated Wed Jul 22 14:46:31 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_reception_air.CREATE_PERSON
     *
     * @return the value of t_airshuttle_reception_air.CREATE_PERSON
     *
     * @mbggenerated Wed Jul 22 14:46:31 CST 2015
     */
    public Integer getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_reception_air.CREATE_PERSON
     *
     * @param createPerson the value for t_airshuttle_reception_air.CREATE_PERSON
     *
     * @mbggenerated Wed Jul 22 14:46:31 CST 2015
     */
    public void setCreatePerson(Integer createPerson) {
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_reception_air.CREATE_TIME
     *
     * @return the value of t_airshuttle_reception_air.CREATE_TIME
     *
     * @mbggenerated Wed Jul 22 14:46:31 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_reception_air.CREATE_TIME
     *
     * @param createTime the value for t_airshuttle_reception_air.CREATE_TIME
     *
     * @mbggenerated Wed Jul 22 14:46:31 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_reception_air.MODIFY_PERSON
     *
     * @return the value of t_airshuttle_reception_air.MODIFY_PERSON
     *
     * @mbggenerated Wed Jul 22 14:46:31 CST 2015
     */
    public Integer getModifyPerson() {
        return modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_reception_air.MODIFY_PERSON
     *
     * @param modifyPerson the value for t_airshuttle_reception_air.MODIFY_PERSON
     *
     * @mbggenerated Wed Jul 22 14:46:31 CST 2015
     */
    public void setModifyPerson(Integer modifyPerson) {
        this.modifyPerson = modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_reception_air.MODIFY_TIME
     *
     * @return the value of t_airshuttle_reception_air.MODIFY_TIME
     *
     * @mbggenerated Wed Jul 22 14:46:31 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_reception_air.MODIFY_TIME
     *
     * @param modifyTime the value for t_airshuttle_reception_air.MODIFY_TIME
     *
     * @mbggenerated Wed Jul 22 14:46:31 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_reception_air.reception_city
     *
     * @return the value of t_airshuttle_reception_air.reception_city
     *
     * @mbggenerated Wed Jul 22 14:46:31 CST 2015
     */
    public String getReceptionCity() {
        return receptionCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_reception_air.reception_city
     *
     * @param receptionCity the value for t_airshuttle_reception_air.reception_city
     *
     * @mbggenerated Wed Jul 22 14:46:31 CST 2015
     */
    public void setReceptionCity(String receptionCity) {
        this.receptionCity = receptionCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_reception_air.reception_school
     *
     * @return the value of t_airshuttle_reception_air.reception_school
     *
     * @mbggenerated Wed Jul 22 14:46:31 CST 2015
     */
    public String getReceptionSchool() {
        return receptionSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_reception_air.reception_school
     *
     * @param receptionSchool the value for t_airshuttle_reception_air.reception_school
     *
     * @mbggenerated Wed Jul 22 14:46:31 CST 2015
     */
    public void setReceptionSchool(String receptionSchool) {
        this.receptionSchool = receptionSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_reception_air.reception_airport
     *
     * @return the value of t_airshuttle_reception_air.reception_airport
     *
     * @mbggenerated Wed Jul 22 14:46:31 CST 2015
     */
    public String getReceptionAirport() {
        return receptionAirport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_reception_air.reception_airport
     *
     * @param receptionAirport the value for t_airshuttle_reception_air.reception_airport
     *
     * @mbggenerated Wed Jul 22 14:46:31 CST 2015
     */
    public void setReceptionAirport(String receptionAirport) {
        this.receptionAirport = receptionAirport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_reception_air.driver_id
     *
     * @return the value of t_airshuttle_reception_air.driver_id
     *
     * @mbggenerated Wed Jul 22 14:46:31 CST 2015
     */
    public Integer getDriverId() {
        return driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_reception_air.driver_id
     *
     * @param driverId the value for t_airshuttle_reception_air.driver_id
     *
     * @mbggenerated Wed Jul 22 14:46:31 CST 2015
     */
    public void setDriverId(Integer driverId) {
        this.driverId = driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_reception_air.car_id
     *
     * @return the value of t_airshuttle_reception_air.car_id
     *
     * @mbggenerated Wed Jul 22 14:46:31 CST 2015
     */
    public Integer getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_reception_air.car_id
     *
     * @param carId the value for t_airshuttle_reception_air.car_id
     *
     * @mbggenerated Wed Jul 22 14:46:31 CST 2015
     */
    public void setCarId(Integer carId) {
        this.carId = carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_reception_air.open_time
     *
     * @return the value of t_airshuttle_reception_air.open_time
     *
     * @mbggenerated Wed Jul 22 14:46:31 CST 2015
     */
    public String getOpenTime() {
        return openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_reception_air.open_time
     *
     * @param openTime the value for t_airshuttle_reception_air.open_time
     *
     * @mbggenerated Wed Jul 22 14:46:31 CST 2015
     */
    public void setOpenTime(String openTime) {
        this.openTime = openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_reception_air.price
     *
     * @return the value of t_airshuttle_reception_air.price
     *
     * @mbggenerated Wed Jul 22 14:46:31 CST 2015
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_reception_air.price
     *
     * @param price the value for t_airshuttle_reception_air.price
     *
     * @mbggenerated Wed Jul 22 14:46:31 CST 2015
     */
    public void setPrice(String price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_reception_air.load_seatNum
     *
     * @return the value of t_airshuttle_reception_air.load_seatNum
     *
     * @mbggenerated Wed Jul 22 14:46:31 CST 2015
     */
    public Integer getLoadSeatnum() {
        return loadSeatnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_reception_air.load_seatNum
     *
     * @param loadSeatnum the value for t_airshuttle_reception_air.load_seatNum
     *
     * @mbggenerated Wed Jul 22 14:46:31 CST 2015
     */
    public void setLoadSeatnum(Integer loadSeatnum) {
        this.loadSeatnum = loadSeatnum;
    }
}