package com.topshare.airshuttle.model.bookDriverProcess;

import java.util.Date;

public class TAirshuttleBookDriverProcess {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_book_driver_process.id
     *
     * @mbggenerated Thu Jul 23 09:15:37 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_book_driver_process.book_driver_id
     *
     * @mbggenerated Thu Jul 23 09:15:37 CST 2015
     */
    private Integer bookDriverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_book_driver_process.review_process_id
     *
     * @mbggenerated Thu Jul 23 09:15:37 CST 2015
     */
    private Integer reviewProcessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_book_driver_process.process_result_desc
     *
     * @mbggenerated Thu Jul 23 09:15:37 CST 2015
     */
    private String processResultDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_book_driver_process.create_time
     *
     * @mbggenerated Thu Jul 23 09:15:37 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_book_driver_process.MODIFY_TIME
     *
     * @mbggenerated Thu Jul 23 09:15:37 CST 2015
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_book_driver_process.id
     *
     * @return the value of t_airshuttle_book_driver_process.id
     *
     * @mbggenerated Thu Jul 23 09:15:37 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_book_driver_process.id
     *
     * @param id the value for t_airshuttle_book_driver_process.id
     *
     * @mbggenerated Thu Jul 23 09:15:37 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_book_driver_process.book_driver_id
     *
     * @return the value of t_airshuttle_book_driver_process.book_driver_id
     *
     * @mbggenerated Thu Jul 23 09:15:37 CST 2015
     */
    public Integer getBookDriverId() {
        return bookDriverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_book_driver_process.book_driver_id
     *
     * @param bookDriverId the value for t_airshuttle_book_driver_process.book_driver_id
     *
     * @mbggenerated Thu Jul 23 09:15:37 CST 2015
     */
    public void setBookDriverId(Integer bookDriverId) {
        this.bookDriverId = bookDriverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_book_driver_process.review_process_id
     *
     * @return the value of t_airshuttle_book_driver_process.review_process_id
     *
     * @mbggenerated Thu Jul 23 09:15:37 CST 2015
     */
    public Integer getReviewProcessId() {
        return reviewProcessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_book_driver_process.review_process_id
     *
     * @param reviewProcessId the value for t_airshuttle_book_driver_process.review_process_id
     *
     * @mbggenerated Thu Jul 23 09:15:37 CST 2015
     */
    public void setReviewProcessId(Integer reviewProcessId) {
        this.reviewProcessId = reviewProcessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_book_driver_process.process_result_desc
     *
     * @return the value of t_airshuttle_book_driver_process.process_result_desc
     *
     * @mbggenerated Thu Jul 23 09:15:37 CST 2015
     */
    public String getProcessResultDesc() {
        return processResultDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_book_driver_process.process_result_desc
     *
     * @param processResultDesc the value for t_airshuttle_book_driver_process.process_result_desc
     *
     * @mbggenerated Thu Jul 23 09:15:37 CST 2015
     */
    public void setProcessResultDesc(String processResultDesc) {
        this.processResultDesc = processResultDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_book_driver_process.create_time
     *
     * @return the value of t_airshuttle_book_driver_process.create_time
     *
     * @mbggenerated Thu Jul 23 09:15:37 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_book_driver_process.create_time
     *
     * @param createTime the value for t_airshuttle_book_driver_process.create_time
     *
     * @mbggenerated Thu Jul 23 09:15:37 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_book_driver_process.MODIFY_TIME
     *
     * @return the value of t_airshuttle_book_driver_process.MODIFY_TIME
     *
     * @mbggenerated Thu Jul 23 09:15:37 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_book_driver_process.MODIFY_TIME
     *
     * @param modifyTime the value for t_airshuttle_book_driver_process.MODIFY_TIME
     *
     * @mbggenerated Thu Jul 23 09:15:37 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}