package com.topshare.airshuttle.model.userManager;

public class TAirshuttleRoleResc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_role_resc.RESC_ID
     *
     * @mbggenerated Tue Jul 14 15:45:05 CST 2015
     */
    private String rescId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_role_resc.ROLE_ID
     *
     * @mbggenerated Tue Jul 14 15:45:05 CST 2015
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_role_resc.RESC_ID
     *
     * @return the value of t_airshuttle_role_resc.RESC_ID
     *
     * @mbggenerated Tue Jul 14 15:45:05 CST 2015
     */
    public String getRescId() {
        return rescId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_role_resc.RESC_ID
     *
     * @param rescId the value for t_airshuttle_role_resc.RESC_ID
     *
     * @mbggenerated Tue Jul 14 15:45:05 CST 2015
     */
    public void setRescId(String rescId) {
        this.rescId = rescId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_role_resc.ROLE_ID
     *
     * @return the value of t_airshuttle_role_resc.ROLE_ID
     *
     * @mbggenerated Tue Jul 14 15:45:05 CST 2015
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_role_resc.ROLE_ID
     *
     * @param roleId the value for t_airshuttle_role_resc.ROLE_ID
     *
     * @mbggenerated Tue Jul 14 15:45:05 CST 2015
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}