package com.topshare.airshuttle.model.userManager;

import java.util.Date;

public class TAirshuttleResc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_resc.ID
     *
     * @mbggenerated Tue Jul 14 15:44:40 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_resc.DESCRIPTION
     *
     * @mbggenerated Tue Jul 14 15:44:40 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_resc.NAME
     *
     * @mbggenerated Tue Jul 14 15:44:40 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_resc.PARENT_ID
     *
     * @mbggenerated Tue Jul 14 15:44:40 CST 2015
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_resc.NODE_ORDER
     *
     * @mbggenerated Tue Jul 14 15:44:40 CST 2015
     */
    private Integer nodeOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_resc.CREATE_PERSON
     *
     * @mbggenerated Tue Jul 14 15:44:40 CST 2015
     */
    private Integer createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_resc.CREATE_TIME
     *
     * @mbggenerated Tue Jul 14 15:44:40 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_resc.MODIFY_PERSON
     *
     * @mbggenerated Tue Jul 14 15:44:40 CST 2015
     */
    private Integer modifyPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_resc.MODIFY_TIME
     *
     * @mbggenerated Tue Jul 14 15:44:40 CST 2015
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_resc.URI
     *
     * @mbggenerated Tue Jul 14 15:44:40 CST 2015
     */
    private String uri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_resc.URICUSTOMER
     *
     * @mbggenerated Tue Jul 14 15:44:40 CST 2015
     */
    private String uriCustomer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_resc.BELONG
     *
     * @mbggenerated Tue Jul 14 15:44:40 CST 2015
     */
    private Integer belong;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_resc.ID
     *
     * @return the value of t_airshuttle_resc.ID
     *
     * @mbggenerated Tue Jul 14 15:44:40 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_resc.ID
     *
     * @param id the value for t_airshuttle_resc.ID
     *
     * @mbggenerated Tue Jul 14 15:44:40 CST 2015
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_resc.DESCRIPTION
     *
     * @return the value of t_airshuttle_resc.DESCRIPTION
     *
     * @mbggenerated Tue Jul 14 15:44:40 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_resc.DESCRIPTION
     *
     * @param description the value for t_airshuttle_resc.DESCRIPTION
     *
     * @mbggenerated Tue Jul 14 15:44:40 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_resc.NAME
     *
     * @return the value of t_airshuttle_resc.NAME
     *
     * @mbggenerated Tue Jul 14 15:44:40 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_resc.NAME
     *
     * @param name the value for t_airshuttle_resc.NAME
     *
     * @mbggenerated Tue Jul 14 15:44:40 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_resc.PARENT_ID
     *
     * @return the value of t_airshuttle_resc.PARENT_ID
     *
     * @mbggenerated Tue Jul 14 15:44:40 CST 2015
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_resc.PARENT_ID
     *
     * @param parentId the value for t_airshuttle_resc.PARENT_ID
     *
     * @mbggenerated Tue Jul 14 15:44:40 CST 2015
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_resc.NODE_ORDER
     *
     * @return the value of t_airshuttle_resc.NODE_ORDER
     *
     * @mbggenerated Tue Jul 14 15:44:40 CST 2015
     */
    public Integer getNodeOrder() {
        return nodeOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_resc.NODE_ORDER
     *
     * @param nodeOrder the value for t_airshuttle_resc.NODE_ORDER
     *
     * @mbggenerated Tue Jul 14 15:44:40 CST 2015
     */
    public void setNodeOrder(Integer nodeOrder) {
        this.nodeOrder = nodeOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_resc.CREATE_PERSON
     *
     * @return the value of t_airshuttle_resc.CREATE_PERSON
     *
     * @mbggenerated Tue Jul 14 15:44:40 CST 2015
     */
    public Integer getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_resc.CREATE_PERSON
     *
     * @param createPerson the value for t_airshuttle_resc.CREATE_PERSON
     *
     * @mbggenerated Tue Jul 14 15:44:40 CST 2015
     */
    public void setCreatePerson(Integer createPerson) {
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_resc.CREATE_TIME
     *
     * @return the value of t_airshuttle_resc.CREATE_TIME
     *
     * @mbggenerated Tue Jul 14 15:44:40 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_resc.CREATE_TIME
     *
     * @param createTime the value for t_airshuttle_resc.CREATE_TIME
     *
     * @mbggenerated Tue Jul 14 15:44:40 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_resc.MODIFY_PERSON
     *
     * @return the value of t_airshuttle_resc.MODIFY_PERSON
     *
     * @mbggenerated Tue Jul 14 15:44:40 CST 2015
     */
    public Integer getModifyPerson() {
        return modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_resc.MODIFY_PERSON
     *
     * @param modifyPerson the value for t_airshuttle_resc.MODIFY_PERSON
     *
     * @mbggenerated Tue Jul 14 15:44:40 CST 2015
     */
    public void setModifyPerson(Integer modifyPerson) {
        this.modifyPerson = modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_resc.MODIFY_TIME
     *
     * @return the value of t_airshuttle_resc.MODIFY_TIME
     *
     * @mbggenerated Tue Jul 14 15:44:40 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_resc.MODIFY_TIME
     *
     * @param modifyTime the value for t_airshuttle_resc.MODIFY_TIME
     *
     * @mbggenerated Tue Jul 14 15:44:40 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_resc.URI
     *
     * @return the value of t_airshuttle_resc.URI
     *
     * @mbggenerated Tue Jul 14 15:44:40 CST 2015
     */
    public String getUri() {
        return uri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_resc.URI
     *
     * @param uri the value for t_airshuttle_resc.URI
     *
     * @mbggenerated Tue Jul 14 15:44:40 CST 2015
     */
    public void setUri(String uri) {
        this.uri = uri;
    }

    public String getUriCustomer() {
		return uriCustomer;
	}

	public void setUriCustomer(String uriCustomer) {
		this.uriCustomer = uriCustomer;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_resc.BELONG
     *
     * @return the value of t_airshuttle_resc.BELONG
     *
     * @mbggenerated Tue Jul 14 15:44:40 CST 2015
     */
    public Integer getBelong() {
        return belong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_resc.BELONG
     *
     * @param belong the value for t_airshuttle_resc.BELONG
     *
     * @mbggenerated Tue Jul 14 15:44:40 CST 2015
     */
    public void setBelong(Integer belong) {
        this.belong = belong;
    }
}