package com.topshare.airshuttle.model.userManager;

import java.util.Date;

public class TAirshuttleUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_user.ID
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_user.USERNAME
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_user.PASSWORD
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_user.SEX
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_user.ENABLED
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    private Integer enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_user.CREATE_PERSON
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    private Integer createPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_user.CREATE_TIME
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_user.MODIFY_PERSON
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    private Integer modifyPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_user.MODIFY_TIME
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_user.DESCRIPTION
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_user.EMAIL
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_user.photot_url
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    private String phototUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_user.desc_myself
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    private Integer descMyself;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_user.lable
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    private Integer lable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_user.telephone
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_user.customer_picUrl
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    private String customerPicurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_user.ID
     *
     * @return the value of t_airshuttle_user.ID
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_user.ID
     *
     * @param id the value for t_airshuttle_user.ID
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_user.USERNAME
     *
     * @return the value of t_airshuttle_user.USERNAME
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_user.USERNAME
     *
     * @param username the value for t_airshuttle_user.USERNAME
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_user.PASSWORD
     *
     * @return the value of t_airshuttle_user.PASSWORD
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_user.PASSWORD
     *
     * @param password the value for t_airshuttle_user.PASSWORD
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_user.SEX
     *
     * @return the value of t_airshuttle_user.SEX
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_user.SEX
     *
     * @param sex the value for t_airshuttle_user.SEX
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_user.ENABLED
     *
     * @return the value of t_airshuttle_user.ENABLED
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    public Integer getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_user.ENABLED
     *
     * @param enabled the value for t_airshuttle_user.ENABLED
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    public void setEnabled(Integer enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_user.CREATE_PERSON
     *
     * @return the value of t_airshuttle_user.CREATE_PERSON
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    public Integer getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_user.CREATE_PERSON
     *
     * @param createPerson the value for t_airshuttle_user.CREATE_PERSON
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    public void setCreatePerson(Integer createPerson) {
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_user.CREATE_TIME
     *
     * @return the value of t_airshuttle_user.CREATE_TIME
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_user.CREATE_TIME
     *
     * @param createTime the value for t_airshuttle_user.CREATE_TIME
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_user.MODIFY_PERSON
     *
     * @return the value of t_airshuttle_user.MODIFY_PERSON
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    public Integer getModifyPerson() {
        return modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_user.MODIFY_PERSON
     *
     * @param modifyPerson the value for t_airshuttle_user.MODIFY_PERSON
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    public void setModifyPerson(Integer modifyPerson) {
        this.modifyPerson = modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_user.MODIFY_TIME
     *
     * @return the value of t_airshuttle_user.MODIFY_TIME
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_user.MODIFY_TIME
     *
     * @param modifyTime the value for t_airshuttle_user.MODIFY_TIME
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_user.DESCRIPTION
     *
     * @return the value of t_airshuttle_user.DESCRIPTION
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_user.DESCRIPTION
     *
     * @param description the value for t_airshuttle_user.DESCRIPTION
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_user.EMAIL
     *
     * @return the value of t_airshuttle_user.EMAIL
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_user.EMAIL
     *
     * @param email the value for t_airshuttle_user.EMAIL
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_user.photot_url
     *
     * @return the value of t_airshuttle_user.photot_url
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    public String getPhototUrl() {
        return phototUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_user.photot_url
     *
     * @param phototUrl the value for t_airshuttle_user.photot_url
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    public void setPhototUrl(String phototUrl) {
        this.phototUrl = phototUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_user.desc_myself
     *
     * @return the value of t_airshuttle_user.desc_myself
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    public Integer getDescMyself() {
        return descMyself;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_user.desc_myself
     *
     * @param descMyself the value for t_airshuttle_user.desc_myself
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    public void setDescMyself(Integer descMyself) {
        this.descMyself = descMyself;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_user.lable
     *
     * @return the value of t_airshuttle_user.lable
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    public Integer getLable() {
        return lable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_user.lable
     *
     * @param lable the value for t_airshuttle_user.lable
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    public void setLable(Integer lable) {
        this.lable = lable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_user.telephone
     *
     * @return the value of t_airshuttle_user.telephone
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_user.telephone
     *
     * @param telephone the value for t_airshuttle_user.telephone
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_user.customer_picUrl
     *
     * @return the value of t_airshuttle_user.customer_picUrl
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    public String getCustomerPicurl() {
        return customerPicurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_user.customer_picUrl
     *
     * @param customerPicurl the value for t_airshuttle_user.customer_picUrl
     *
     * @mbggenerated Tue Jul 14 14:24:39 CST 2015
     */
    public void setCustomerPicurl(String customerPicurl) {
        this.customerPicurl = customerPicurl;
    }
}