package com.topshare.airshuttle.model.userManager;

public class TAirshuttleUserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_user_role.USER_ID
     *
     * @mbggenerated Tue Jul 14 15:41:27 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_airshuttle_user_role.ROLE_ID
     *
     * @mbggenerated Tue Jul 14 15:41:27 CST 2015
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_user_role.USER_ID
     *
     * @return the value of t_airshuttle_user_role.USER_ID
     *
     * @mbggenerated Tue Jul 14 15:41:27 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_user_role.USER_ID
     *
     * @param userId the value for t_airshuttle_user_role.USER_ID
     *
     * @mbggenerated Tue Jul 14 15:41:27 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_airshuttle_user_role.ROLE_ID
     *
     * @return the value of t_airshuttle_user_role.ROLE_ID
     *
     * @mbggenerated Tue Jul 14 15:41:27 CST 2015
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_airshuttle_user_role.ROLE_ID
     *
     * @param roleId the value for t_airshuttle_user_role.ROLE_ID
     *
     * @mbggenerated Tue Jul 14 15:41:27 CST 2015
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}